### ISSUE TITLE
Wrong license

### ISSUE THREAD

**Issue by MWHunter** [jakobkmar/KSpigot#29]
Currently KSpigot is licensed under Apache.  However, you are subclassing JavaPlugin - which is licensed under bukkit's GPL license

https://github.com/jakobkmar/KSpigot/blob/47c220f65b4e020275d8deaf92923018332686a1/src/main/kotlin/net/axay/kspigot/main/KSpigot.kt#L36

This creates a derivative work, shown from GPL's FAQ: https://www.gnu.org/licenses/gpl-faq.en.html#OOPLang

Therefore, KSpigot must be licensed under GPL rather than Apache in order to continue using Bukkit without copyright infringement.

**Comment by jakobkmar** [comment]
CraftBukkit as part of Spigot is licensed under LGPL since 2011.
Btw, GPL is not even compatible with Minecraft, therefore even Bukkit can't be licensed under it without any additions to the license.
But yeah, see this commit from 02 Jan 2011:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/5c37168fc3c52e36b6fff0dc72806ac81345cd1f#LGPL.txt

**Comment by jakobkmar** [comment]
This is a very interesting part of hMod / Bukkits / Spigots history, you can read more about this [here](https://minecraft.fandom.com/de/wiki/Bukkit#Die_hMod-Kontroverse), but you have to translate it though.

**Comment by mbax** [comment]
You have your ordering backwards. Bukkit is its own thing separate from Mojang code and is GPL licensed, and CraftBukkit is an implementation of Bukkit onto Mojang's code, an action which is incompatible with licensing and therefore cannot be distributed (thus the DMCA takedown once Mojang revealed they did not in fact allow this despite owning it). CraftBukkit's problems do not make Bukkit's license invalid. As for the history, I was there. I was a part of the team maintaining the project before its end.

While I may be one of the folks who could actually cause you trouble, as one of the contributors to Bukkit, I lack the time and motivation and money to pursue enforcement actions so instead I just ask nicely that you honor Bukkit's memory by at least keeping your works open source, as you're doing presently. ❤️

**Comment by jakobkmar** [comment]
KSpigot will always be open source. Also, I already considered switching to the GPL, but that would cause that others can't use this library anymore.

The accepted state in the spigot community seems to be that any open source license is valid, even if this might not be quite correct. I don't know, this thing is complicated, and I didn't think that this discussion from back then reaches this library today.

**Comment by jakobkmar** [comment]
May I ask you why you think that KSpigot won't stay open source?

**Comment by jakobkmar** [comment]
All API contributors agreed with switching to GPL-3.0.

**Comment by retrooper** [comment]
> You have your ordering backwards. Bukkit is its own thing separate from Mojang code and is GPL licensed, and CraftBukkit is an implementation of Bukkit onto Mojang's code, an action which is incompatible with licensing and therefore cannot be distributed (thus the DMCA takedown once Mojang revealed they did not in fact allow this despite owning it). CraftBukkit's problems do not make Bukkit's license invalid. As for the history, I was there. I was a part of the team maintaining the project before its end.
> 
> While I may be one of the folks who could actually cause you trouble, as one of the contributors to Bukkit, I lack the time and motivation and money to pursue enforcement actions so instead I just ask nicely that you honor Bukkit's memory by at least keeping your works open source, as you're doing presently. ❤️

I totally agree with you, appreciate people like you clearing it up, but why don't you speak up about this and tell much more people. You for sure know there are so many people violating your license, especially unknowingly. My impression is the average Spigot developer doesn't know much about licensing, and believes they have freedom to choose any license.
