### ISSUE TITLE
Change all legacy strings to adventure Components

### ISSUE THREAD

**Issue by TheSirCororo** [jakobkmar/KSpigot#36]
What about change all legacy strings to adventure components? And add adventure utils (for ex. String.contentToComponent() = Component.text(this) and String.legacyToComponent() = LegacyComponentSerializer.legacyAmpersand().deserialize(this) and Component.toLegacy() = LegacyComponentSerializer.legacyAmpersand().serialize(this))

**Comment by jakobkmar** [comment]
The change to Adventure has already happened with #34, it has just not been released yet.

However, the extension functions you are suggesting are still missing, they can be added as well.
