### ISSUE TITLE
suggestListSuspending() with player list causes critical error

### ISSUE THREAD

**Issue by TheSirCororo** [jakobkmar/KSpigot#37]
I have suggestions:
```kt
suggestListSuspending {
     Bukkit.getOnlinePlayers().map { it.name }
}
```
When I executes any command with that suggestions, I get crash with error https://pastebin.com/XnjtZ9zf
I have Kotlin in my jar

**Comment by l4zs** [comment]
You'll have to add the following libraries to your plugin.yml:
"org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0"
"org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.0"

**Comment by jakobkmar** [comment]
What @l4zs says is correct, the paperweight version kspigot used when publishing at that time had a bug which broke transitive dependencies.
