### ISSUE TITLE
Publish new version to maven central

### ISSUE THREAD

**Issue by mooziii** [jakobkmar/KSpigot#43]
kspigot 1.18.0 commands dont work on 1.18.2 so please publish the new version 😄

**Comment by l4zs** [comment]
maven central it is

**Comment by mooziii** [comment]
i dont see 1.18.2 or 1.18.1 ![img](https://i.imgur.com/fIR5gT5.png)

**Comment by jakobkmar** [comment]
@mooziii yes it is not yet released, and @l4zs just said that the title is wrong, you probably want it to be on maven central not maven local

and yeah I am working on it, just need some more time - have to finish something else first

**Comment by mooziii** [comment]
okay all good i'll just publish it into my local repo 👍

**Comment by jakobkmar** [comment]
It is now available: https://repo1.maven.org/maven2/net/axay/kspigot/1.18.2/
